name: ColoredGroups
author: Nick Porillo 
main: net.porillo.ColoredGroups
website: http://porillo.net
version: ${project.version}
softdepend: [Vault]
commands:
  coloredgroups:
    aliases: [cg, color]