name: ColoredGroups
author: milkywayz 
main: net.milkycraft.ColoredGroups
website: http://milkycraft.net
version: 1.5.1

commands:
    coloredgroups:
      aliases: cg
      description: The colored groups command

  